### ISSUE TITLE
Feature - access to DAC channels?

### ISSUE THREAD

**Issue by stevejryan** [fcollman/abfload#3]
Are there any plans to give access to the current injection waveform for episodic protocols?  

I used to access ABF data using compiled matlab code from a group at ICL, but that code is no longer actively developed and has not kept up with the new ABF 2 file format.  Some of my existing analysis code uses the current steps to construct F/I plots, that sort of thing.

Apologies if this is not the preferred way to submit this kind of thing. 

Thank you both for your work on this repository!

**Comment by fcollman** [comment]
Perhaps! Could you maybe create and upload to somewhere publicly accessible (dropbox link, google drive, etc) a small example file and a screen shot of what the correct answer looks like to aid in development?

**Comment by stevejryan** [comment]
Will do, thanks!

**Comment by hhentschke** [comment]
The beginnigs of code allowing extraction of command waveforms in episodic recording mode were already there; I revamped the code and placed it in branch DAC-channel-info. It works with the files I deal with (abf version >= 2.0, one or two recorded and stimulated channels, simple step stimulation protocols). However, this is just a first shot, there is more information on analog output to be extracted, which may be necessary for recordings with more complex stimulation protocols. Feedback welcome!

**Comment by stevejryan** [comment]
Great!  This looks like it will be a good start for me.  By way of example, I uploaded a Dropbox folder containing the sort of data I've worked with in the past - https://www.dropbox.com/sh/q9em5m1q1266hgv/AAA0c1dTpvFaAsncH7WCyXuTa?dl=0

The short version is that the code I'm used to outputs a data matrix for the DAC channels that's the same shape as the analog data matrix, so you're basically getting a current injection value that corresponds to each sample.  This format is convenient to work with.  As Harald suggested, for simple protocols, like the one in the linked folder, it would probably be easy enough to reconstruct that matrix from the data provided in your h.DACEpoch in the new branch, but for more complex protocols that might get out of hand.

![dacexample figure](https://user-images.githubusercontent.com/13875539/29682657-cf0f5760-88d9-11e7-95c5-b3c789b0948e.png)

**Comment by hhentschke** [comment]
OK, nice that it (kind of) works for you! I see the point that an output in the form of a ready-to-plot matrix would be more convenient, but I'd leave that part to each user and focus on the indispensable. So let's close the issue for now, and merge branches, until there is actual need for more complete and/or sophisticated DAC parameter output. Agreed?

**Comment by stevejryan** [comment]
Agreed!  And thank you again for the quick response.

**Comment by stevejryan** [comment]
Hi - 
I've started building a function to generate the DAC waveforms as discussed above and I've run into a bit of a snag.  Clampex doesn't start the 1st Epoch at the 1st sample of data acquisition, there appears to be a variable lag of some number of samples.  As far as I can tell, the duration of the epochs is exact right down to the sample, but I don't see a way to find the start time of the first epoch.

Is that something abfload already produces and I'm just missing it?  

Thanks,
-Steve

**Comment by hhentschke** [comment]
Hi Steve,
you've just opened an old wound in the flesh - I realized the issue you describe a long time ago, but hadn't found a hint in the abf documentation back then and therefore resorted to circumventing the problem (by specifying the sample at which stimulations begins manually, which is fine if you process many files resulting from the same stimulation protocol). I can't offer a solution off-hand. I will look into the issue, but this will certainly take some time. Should you come across some promising hints, let me know please!

**Comment by stevejryan** [comment]
Understood =)

I'll keep working on it.  If it's any consolation, there a solution out there somewhere!  The compiled package I pulled out of sigTOOL to do my analyses before it got out of date seemed to solve this problem somehow.

Thanks again,
-Steve

**Comment by fcollman** [comment]
can you point to that codebase somehow? Probably reading it will provide a
good hint.

**Comment by stevejryan** [comment]
The most recent version of it can be downloaded here - https://sourceforge.net/projects/sigtool/

The specific part we're interested in is in ~\sigTOOL_Version_0.95\sigTOOL\sigTOOL Neuroscience Toolkit\File\menu_Import\group_NeuroScience File Formats\axon

There are a set of mex32 files that can be called from matlab to access the different components of a specified ABF file, using the abffio.dll provided by Axon.  Specifically, the source code is in the .\SourceCode directory.  

I've also put that 'axon' directory in my Dropbox in case that's more convenient for you - https://www.dropbox.com/s/vi1gtkgnno7l3cj/axon.zip?dl=0

**Comment by fcollman** [comment]
ah... so ultimately I think this feature is likely implemented by the .dll
feature given by axon, and so we need access to that C code that compiled
it to find how they got that information out of the abf.  At some point
that c code was available on the web. I will try to look for it again.

**Comment by hhentschke** [comment]
Steve, I may have found a solution; at least it works with the file you provided in your dropbox and a range of other files I tested. Search the code for .firstHolding; there is some explanation of how I found the (ridiculously simple) provisional solution. I'm not sure yet that it's a general solution, that's why I placed it in the DAC-channel-info branch for now.

**Comment by stevejryan** [comment]
Great, I'll test this ASAP and get back to you

**Comment by hhentschke** [comment]
OK. I closed the issue accidentally, but maybe that's a good omen :)

**Comment by hhentschke** [comment]
I've merged this branch to the master branch because there had been no feedback and other issues with abfload have come up. Closing this issue now, please open it up if there is something amiss or not working.
